### ISSUE TITLE
New benchmark site at Cala Millor (Mallorca, Spain)

### ISSUE THREAD

**Issue by kvos** [kvos/SDS_Benchmark#4]
Post to discuss how to include this new benchmark site at Cala Millor.

**Comment by ddbuscombe** [comment]
Hi there! I was wondering, did anyone figure this out? The paper links to https://www.caib.es/sites/adaptcalamillor/en/n/socib_researchers_publish_ten_years_of_sustained_morphodynamic_data_of_cala_millor_beach_mallorca/ but I don't see how to access the data. Thanks, and I hope you're doing well!

**Comment by ddbuscombe** [comment]
It is now available https://apps.socib.es/data-catalog/#/data-products/cala-millor-coastal-station-enl
